#spring.profiles.active=pro
#security.user.name=admin
#security.user.password=test
#
#server.port=8081
#server.context-path=/demo

#mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/caredevice
##jdbc.url=jdbc:mysql://localhost:3306/caredevice
##jdbc.url=jdbc:sqlserver://211.154.149.163:1433;DatabaseName=jydb
#spring.datasource.username=root
#spring.datasource.password=lfp1991lfp
##jdbc.password=Ghero152505
#spring.datasource.tomcat.max-active=2
#spring.datasource.tomcat.max-idle=5
#spring.datasource.tomcat.min-idle=1
#spring.datasource.tomcat.initial-size=3
#spring.datasource.tomcat.max-wait=3000
##JPA Configuration:
#spring.jpa.database=MySQL
spring:
  profiles:
    active: dev